# wordpress/docker-compose.yml
services:
  wordpress:
    image: wordpress:php8.0-apache
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "Mrluchanglong@163.com"
      WORDPRESS_DB_NAME: wordpress
    user: "33:33"
    networks:
      - web_network
    volumes:
      - ${STATIC_HTML_PATH}/wordpress:/var/www/html
      - ./servername.conf:/etc/apache2/conf-available/servername.conf
    env_file:
      - .env

networks:
  web_network:
    external: true