services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Mrluchanglong@163.com
      WORDPRESS_DB_NAME: wordpress
    user: "33:33"
    volumes:
      - ${STATIC_HTML_PATH}/wordpress:/var/www/html
    networks:
      - web_network
    restart: always
    env_file:
      - .env

networks:
  web_network:
    external: true