services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Mrluchanglong@163.com"
      MYSQL_DATABASE: wordpress
      TZ: Asia/Shanghai
    volumes:
      - ./conf/mysql.conf:/etc/mysql/conf.d/custom.cnf
      - ./init:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"
    networks:
      - web_network
    restart: always
    ports:
      - "3306:3306"
    command: 
      --lower_case_table_names=1
      --performance-schema=OFF
      --default-authentication-plugin=mysql_native_password
      --host_cache_size=0

networks:
  web_network:
    external: true